title: Akhil Perincherry # your name (or website title) here
logo: "/images/profilePicture2.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an ML research engineer at Ford Motor Company automated driving where I work on computer vision and machine learning for perception features in the context of automated driving. Most of my work is on camera images and LiDAR point clouds.
  <br><br>
  I completed my masters from University of Florida in 2016 specializing in computer vision and machine learning, and have been at Ford since then.
  <br><br>
  In my free time I enjoy playing/watching soccer, kickboxing, hiking (waterfall hikes are the best!) and practically any outdoor sport.
  <br><br>
  <a href="mailto:akhil_nr@hotmail.com">Email</a> |
  
  <a href="https://www.linkedin.com/in/espanade/">LinkedIn</a> |
 
  <a href="https://github.com/akhilperincherry">Github</a> 
  <br> 
  <a href="https://scholar.google.com/citations?user=wPNd0xkAAAAJ&hl=en">Google Scholar</a> |

  <a href="https://twitter.com/aperinch">Twitter</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
